title: Simranjeet Kaur Gill
description: Web & Security Engineer
site_title: '@abhn - Abhishek Nagekar'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: SimranjeetG
blog_url: https://www.nagekar.com
email: simranjeetkaur9340@gmail.com
keybase_username: 
twitter_username: 
reddit_username: 

# absolute or relative
profile_picture: assets/images/Picture.jpg

# Google Analytics ID
google_analytics: 